# Preface (2nd edition) {-}

Spatio-Temporal Methods in Environmental Epidemiology using R is the first book of its kind to specifically address the interface between environmental epidemiology and spatio-temporal modeling. In response to the growing need for collaboration between statisticians and environmental epidemiologists, the book links recent developments in spatio-temporal methodology with epidemiological applications. Drawing on real-life problems, it provides the tools required to exploit advances in methodology when assessing the health risks associated with environmental hazards. Clear guidelines are given to enable the implementation of methodology and estimation of risks in practice.

Designed for graduate students in both epidemiology and statistics, the text covers a wide range of topics, from an introduction to epidemiological principles and the foundations of spatio-temporal modeling to new directions for research. It describes traditional and Bayesian approaches and presents the theory of spatial, temporal, and spatio-temporal modeling in the context of its application to environmental epidemiology. The text includes practical examples together with embedded R code and details of specific R packages and the use of other software including Nimble, Stan, and INLA. Online resources associated with the book provide additional code, data, examples, exercises, lab projects, and more.

Representing a major new direction in environmental epidemiology, this book—in full color throughout—underscores the increasing need to consider dependencies in both space and time when modeling epidemiological data. Students will learn how to identify and model patterns in spatio-temporal data and to exploit dependencies over both space and time in order to reduce bias and inefficiency.

From this book the reader will have gained an understanding of the following topics:

- The basic concepts of epidemiology and the estimation of risks associated with environmental hazards.
- Hierarchical modelling with a Bayesian framework.
- The theory of spatial, temporal and spatio--temporal process needed for environmental health risk analysis.
- Fundamental questions related to the nature and role of uncertainty in environmental epidemiology and methods which may help answer those questions.
- Important areas of application within environmental epidemiology together with strategies for building the models that are needed and coping with challenges that arise.
- Methods and software for the analysis and visualisation of environmental and health. - Examples of R and WinBUGS code are given throughout the book and, together with data for the examples the code, are included in the online resources.
- Offer a variety of exercises, both theoretical and practical, to assist in the development of the skills needed to perform spatio--temporal analyses.
- New frontiers and areas of current and future research.
