# Environmental hazards-spatial models {#hazards}


The chapter contains the theory required for handling time series data. From this chapter, the reader will have gained an understanding of the following topics:

- That a temporal process consists of both low and high frequency components, the former playing a key role in determining long-term trends while the latter may be associated with shorter-term changes.
- Techniques for the exploratory analysis of the data generated by the temporal process, including the ACF (correlogram) and PACF (periodogram).
- Models for irregular (high frequency) components after the regular components (trend) have been removed.
- Methods for forecasting, including exponential smoothing and ARIMA modelling.
- The state space modelling approach, which sits naturally within a Bayesian setting and which provides a general framework for most of the classical time series models and many more besides.
- Implementing time series processes within a Bayesian hierarchical framework.
